language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
   - pip install coveralls

script:
  - python -m  unittest discover -s  Tests
  - pytest --cov=YourModule/
after_success:
  - coveralls
branches:
  only:
    - master
    - development